use_frameworks!

target 'MoyaMapper_Example' do
    
  # MoyaMapper
  pod 'MoyaMapper', :path => '../'
  pod 'MoyaMapper/Rx', :path => '../'
  pod 'MoyaMapper/RxCache', :path => '../'
  
  # Rx
  pod 'RxCocoa'
  pod 'RxDataSources'

  target 'MoyaMapper_Tests' do
    inherit! :search_paths

    
  end
end
